# These are supported funding model platforms

github: [yourusername]
patreon: # Replace with your Patreon
open_collective: # Replace with your Open Collective
ko_fi: # Replace with your Ko-fi
liberapay: # Replace with your Liberapay
issuehunt: # Replace with your IssueHunt
otechie: # Replace with your Otechie
custom: # Replace with a custom URL
