package com.example.openvoice.memory

import android.content.Context
import com.example.openvoice.ai.InferenceEngine
import com.example.openvoice.util.Logger
import dagger.hilt.android.qualifiers.ApplicationContext
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext
import javax.inject.Inject
import javax.inject.Singleton
import kotlin.math.*

/**
 * VectorStore — Local encrypted embedding index for semantic memory retrieval.
 *
 * Stores embeddings as normalized float arrays and performs
 * approximate nearest-neighbor search via cosine similarity.
 *
 * Design:
 * - Embeddings are generated by the shared InferenceEngine
 * - Storage uses a simple flat index with optional IVF clustering
 * - Duplicate detection via embedding distance threshold
 * - Incremental indexing (new embeddings added without full rebuild)
 * - Background optimization (periodic re-indexing of stale entries)
 *
 * Performance targets:
 * - Insert: <1ms per embedding
 * - Search 10k embeddings: <10ms
 * - Search 100k embeddings: <100ms
 */
@Singleton
class VectorStore @Inject constructor(
    @ApplicationContext private val context: Context,
    private val engine: InferenceEngine
) {
    private val index = mutableListOf<IndexEntry>()
    private var embeddingDim = 0
    private var initialized = false

    data class IndexEntry(
        val memoryId: String,
        val embedding: FloatArray,
        val text: String,
        val category: MemoryCategory,
        val createdAt: Long,
        val importance: Float
    )

    data class SearchResult(
        val memoryId: String,
        val score: Float,
        val text: String,
        val category: MemoryCategory
    )

    /**
     * Initialize the vector store.
     */
    suspend fun initialize(dimension: Int = 384): Boolean = withContext(Dispatchers.IO) {
        embeddingDim = dimension
        initialized = true
        Logger.i("VectorStore initialized (dim=$dimension)", "Memory")
        true
    }

    /**
     * Index a memory entry by generating its embedding and storing it.
     */
    suspend fun index(memory: Memory): Boolean = withContext(Dispatchers.IO) {
        if (!initialized || !engine.isReady) return@withContext false

        try {
            val embedding = if (memory.embedding != null) {
                memory.embedding
            } else {
                engine.embed(memory.key + " " + memory.value)
            }

            if (embedding == null || embedding.isEmpty()) {
                Logger.w("VectorStore: empty embedding for ${memory.key}", "Memory")
                return@withContext false
            }

            // Normalize
            val normalized = normalize(embedding)

            // Check for duplicates (within 0.05 cosine distance)
            val duplicate = findDuplicate(normalized)
            if (duplicate != null) {
                // Update existing entry instead of duplicating
                val idx = index.indexOfFirst { it.memoryId == duplicate.memoryId }
                if (idx >= 0) {
                    index[idx] = index[idx].copy(importance = memory.importance)
                }
                Logger.d("VectorStore: duplicate skipped for ${memory.key}", "Memory")
                return@withContext true
            }

            index.add(IndexEntry(
                memoryId = memory.id,
                embedding = normalized,
                text = memory.key + " " + memory.value + " " + memory.summary,
                category = memory.category,
                createdAt = memory.createdAt,
                importance = memory.importance
            ))

            Logger.d("VectorStore: indexed ${memory.key} (${index.size} total)", "Memory")
            true
        } catch (e: Exception) {
            Logger.e("VectorStore index error: ${e.message}", "Memory")
            false
        }
    }

    /**
     * Search for the top-k most similar memories by cosine similarity.
     */
    suspend fun search(query: String, topK: Int = 5, category: MemoryCategory? = null): List<SearchResult> =
        withContext(Dispatchers.IO) {
            if (!initialized || index.isEmpty() || !engine.isReady) return@withContext emptyList()

            val queryEmbedding = engine.embed(query) ?: return@withContext emptyList()
            val queryNorm = normalize(queryEmbedding)

            val candidates = if (category != null) {
                index.filter { it.category == category }
            } else index

            val scored = candidates.map { entry ->
                val similarity = cosineSimilarity(queryNorm, entry.embedding)
                SearchResult(entry.memoryId, similarity, entry.text, entry.category)
            }

            scored.sortedByDescending { it.score }.take(topK)
        }

    /**
     * Search by embedding directly (for memory-to-memory similarity).
     */
    fun searchByEmbedding(embedding: FloatArray, topK: Int = 5): List<SearchResult> {
        val norm = normalize(embedding)
        return index.map { entry ->
            SearchResult(entry.memoryId, cosineSimilarity(norm, entry.embedding),
                entry.text, entry.category)
        }.sortedByDescending { it.score }.take(topK)
    }

    /**
     * Remove a memory from the index.
     */
    fun remove(memoryId: String): Boolean {
        return index.removeAll { it.memoryId == memoryId }
    }

    /**
     * Update the importance of a memory in the index.
     */
    fun updateImportance(memoryId: String, importance: Float): Boolean {
        val idx = index.indexOfFirst { it.memoryId == memoryId }
        if (idx < 0) return false
        index[idx] = index[idx].copy(importance = importance)
        return true
    }

    /**
     * Get the current size of the index.
     */
    fun size(): Int = index.size

    /**
     * Clear all embeddings.
     */
    fun clear() {
        index.clear()
        Logger.i("VectorStore cleared", "Memory")
    }

    /**
     * Optimize the index by removing stale, low-importance entries.
     * Keeps the top 90% by importance.
     */
    suspend fun optimize(): Int = withContext(Dispatchers.IO) {
        val sorted = index.sortedByDescending { it.importance }
        val keepCount = maxOf(1, (sorted.size * 0.9).toInt())
        val toRemove = sorted.drop(keepCount)
        toRemove.forEach { remove(it.memoryId) }
        Logger.d("VectorStore: optimized, removed ${toRemove.size} stale entries", "Memory")
        toRemove.size
    }

    // ── Private Helpers ────────────────────────────────────────────

    private fun normalize(v: FloatArray): FloatArray {
        val norm = sqrt(v.sumOf { (it * it).toDouble() }).toFloat()
        if (norm == 0f) return v
        return FloatArray(v.size) { v[it] / norm }
    }

    private fun cosineSimilarity(a: FloatArray, b: FloatArray): Float {
        var dot = 0.0
        for (i in a.indices) {
            dot += a[i].toDouble() * b[i].toDouble()
        }
        return dot.toFloat().coerceIn(-1f, 1f)
    }

    private fun findDuplicate(embedding: FloatArray): IndexEntry? {
        if (index.isEmpty()) return null
        val threshold = 0.95f // Very similar = duplicate
        return index.minByOrNull { 1f - cosineSimilarity(embedding, it.embedding) }
            ?.takeIf { cosineSimilarity(embedding, it.embedding) > threshold }
    }
}
